FROM node:20.11.0-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
RUN npx ngcc --properties es2023 browser module main --first-only --create-ivy-entry-points
COPY . .
RUN npm run build
FROM nginx:latest
COPY default.conf /etc/nginx/conf.d
COPY --from=build /app/dist/JaverianaImpacta/browser/ /usr/share/nginx/html
COPY wait-for-it.sh /usr/local/bin/wait-for-it.sh
RUN chmod +x /usr/local/bin/wait-for-it.sh
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
