insert into javeriana_impacta.actividad (ID, DESCRIPCION)
values  (1, 'Charla informativa'),
        (19, 'Foro'),
        (3, 'Jornada de limpieza'),
        (18, 'Panel de experiencias'),
        (4, 'Seguimiento-Semana 1'),
        (13, 'Seguimiento-Semana 10'),
        (14, 'Seguimiento-Semana 11'),
        (15, 'Seguimiento-Semana 12'),
        (16, 'Seguimiento-Semana 13'),
        (17, 'Seguimiento-Semana 14'),
        (5, 'Seguimiento-Semana 2'),
        (6, 'Seguimiento-Semana 3'),
        (7, 'Seguimiento-Semana 4'),
        (8, 'Seguimiento-Semana 5'),
        (9, 'Seguimiento-Semana 6'),
        (10, 'Seguimiento-Semana 7'),
        (11, 'Seguimiento-Semana 8'),
        (12, 'Seguimiento-Semana 9'),
        (2, 'Taller de sensibilización');